@processBaseUrl = http://localhost:8000

### Process an image
# @name processImage
POST {{processBaseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
--boundary--

### Process a PDF document
# @name processPDF
POST {{processBaseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary2

--boundary2
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
--boundary2--

### Get the status of the image process
# @name getImageStatus
GET {{processImage.response.body.$.results_url}}

### Get the status of the PDF process
# @name getPDFStatus
GET {{processPDF.response.body.$.results_url}}
