@processBaseUrl = http://localhost:8000

### Process a file
# @name processFile
POST {{processBaseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./api-processing/example.pdf
--boundary--

### Get the status of the process
# @name getStatus
GET {{processImage.response.body.$.results_url}}
