@processBaseUrl = http://localhost:8000

### Process a PDF document
# @name processPdf
POST {{processBaseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
--boundary--

### Get the status of the process
# @name getStatus
GET {{processPdf.response.body.$.results_url}}
