@baseUrl = http://localhost:8000

### Upload an image
# @name uploadImage
POST {{baseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
--boundary--

### Upload a PDF
# @name uploadPdf
POST {{baseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundarypdf

--boundarypdf
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
--boundarypdf--