{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-apps.fullname" . }}-frontend
  labels:
    {{- include "demo-apps.labels" . | nindent 4 }}
    {{- include "demo-apps.componentLabels" "frontend" | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-apps.selectorLabels" . | nindent 6 }}
      {{- include "demo-apps.componentLabels" "frontend" | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "demo-apps.selectorLabels" . | nindent 8 }}
        {{- include "demo-apps.componentLabels" "frontend" | nindent 8 }}
    spec:
      serviceAccountName: {{ include "demo-apps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: frontend
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "demo-apps.image" .Values.frontend.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: REACT_APP_API_PROCESSING_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: react-app-api-processing-url
        - name: REACT_APP_API_STATUS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: react-app-api-status-url
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: environment
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: region
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-cache
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
