# Development environment values
global:
  environment: "dev"
  region: "eastus"
  imageTag: "latest"
  registry: "your-dev-registry.azurecr.io"

# Resource limits for development
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"

# Lower replica counts for dev
apiProcessing:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    STORAGE_ACCOUNT_URL: "https://devstorageaccount.blob.core.windows.net"
    STORAGE_CONTAINER: "dev-images"
    PROCESSED_BASE_URL: "https://dev-api.example.com"
    SERVICEBUS_FQDN: "dev-servicebus.servicebus.windows.net"
    SERVICEBUS_QUEUE: "dev-processing-queue"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=your-dev-key"

apiStatus:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    COSMOS_ACCOUNT_URL: "https://dev-cosmos.documents.azure.com:443/"
    COSMOS_DB_NAME: "dev-database"
    COSMOS_CONTAINER_NAME: "dev-results"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=your-dev-key"

frontend:
  replicaCount: 1
  env:
    REACT_APP_API_PROCESSING_URL: "https://dev-api.example.com/api/processing"
    REACT_APP_API_STATUS_URL: "https://dev-api.example.com/api/status"

# HPA settings for dev
hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Ingress for dev (DEPRECATED - migrate to Gateway API)
ingress:
  hosts:
    - host: dev-demo-apps.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api/processing
          pathType: Prefix
          service: api-processing
        - path: /api/status
          pathType: Prefix
          service: api-status
  tls:
    - secretName: dev-demo-apps-tls
      hosts:
        - dev-demo-apps.example.com

# Gateway API for dev (RECOMMENDED)
gateway:
  enabled: false  # Set to true to use Gateway API instead of Ingress
  hostname: "dev-demo-apps.example.com"
  tls:
    secretName: "dev-demo-apps-tls"
