{{- if .Values.apiProcessing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-apps.fullname" . }}-api-processing
  labels:
    {{- include "demo-apps.labels" . | nindent 4 }}
    {{- include "demo-apps.componentLabels" "api-processing" | nindent 4 }}
spec:
  replicas: {{ .Values.apiProcessing.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-apps.selectorLabels" . | nindent 6 }}
      {{- include "demo-apps.componentLabels" "api-processing" | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "demo-apps.selectorLabels" . | nindent 8 }}
        {{- include "demo-apps.componentLabels" "api-processing" | nindent 8 }}
    spec:
      serviceAccountName: {{ include "demo-apps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: api-processing
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "demo-apps.image" .Values.apiProcessing.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.apiProcessing.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: STORAGE_ACCOUNT_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-storage-account-url
        - name: STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-storage-container
        - name: PROCESSED_BASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-processed-base-url
        - name: SERVICEBUS_FQDN
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-servicebus-fqdn
        - name: SERVICEBUS_QUEUE
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-servicebus-queue
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "demo-apps.fullname" . }}-secret
              key: api-processing-appinsights-connection-string
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: api-processing-cors-origin
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: environment
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: {{ include "demo-apps.fullname" . }}-config
              key: region
        resources:
          {{- toYaml .Values.apiProcessing.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-cache
          mountPath: /var/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-cache
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
