apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-apps.fullname" . }}-secret
  labels:
    {{- include "demo-apps.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.apiProcessing.enabled }}
  # API Processing Secrets (base64 encoded)
  api-processing-storage-account-url: {{ .Values.apiProcessing.env.STORAGE_ACCOUNT_URL | b64enc | quote }}
  api-processing-storage-container: {{ .Values.apiProcessing.env.STORAGE_CONTAINER | b64enc | quote }}
  api-processing-processed-base-url: {{ .Values.apiProcessing.env.PROCESSED_BASE_URL | b64enc | quote }}
  api-processing-servicebus-fqdn: {{ .Values.apiProcessing.env.SERVICEBUS_FQDN | b64enc | quote }}
  api-processing-servicebus-queue: {{ .Values.apiProcessing.env.SERVICEBUS_QUEUE | b64enc | quote }}
  api-processing-appinsights-connection-string: {{ .Values.apiProcessing.env.APPLICATIONINSIGHTS_CONNECTION_STRING | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.apiStatus.enabled }}
  # API Status Secrets (base64 encoded)
  api-status-cosmos-account-url: {{ .Values.apiStatus.env.COSMOS_ACCOUNT_URL | b64enc | quote }}
  api-status-cosmos-db-name: {{ .Values.apiStatus.env.COSMOS_DB_NAME | b64enc | quote }}
  api-status-cosmos-container-name: {{ .Values.apiStatus.env.COSMOS_CONTAINER_NAME | b64enc | quote }}
  api-status-appinsights-connection-string: {{ .Values.apiStatus.env.APPLICATIONINSIGHTS_CONNECTION_STRING | b64enc | quote }}
  {{- end }}
