apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demo-apps-prod-eastus

resources:
  - ../../clusters/eastus

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
  - configmap-patch.yaml
  - secret-patch.yaml

patches:
  # Increase replicas for production
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  
  # Increase resource limits for production
  - target:
      kind: Deployment
      name: demo-apps-api-processing
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
  
  - target:
      kind: Deployment
      name: demo-apps-api-status
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
  
  - target:
      kind: Deployment
      name: demo-apps-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
  
  # Adjust HPA for production
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
      - op: replace
        path: /spec/metrics/1/resource/target/averageUtilization
        value: 70
  
  # Adjust PDB for production
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 2
  
  # Add anti-affinity for production
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - demo-apps
                topologyKey: kubernetes.io/hostname

images:
  - name: api-processing
    newTag: stable
  - name: api-status
    newTag: stable
  - name: frontend
    newTag: stable
