apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-apps-api-processing
  namespace: demo-apps
  labels:
    app.kubernetes.io/name: demo-apps
    app.kubernetes.io/component: api-processing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-apps-api-processing
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-apps-api-status
  namespace: demo-apps
  labels:
    app.kubernetes.io/name: demo-apps
    app.kubernetes.io/component: api-status
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-apps-api-status
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-apps-frontend
  namespace: demo-apps
  labels:
    app.kubernetes.io/name: demo-apps
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-apps-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
