apiVersion: v1
kind: Secret
metadata:
  name: demo-apps-secret
  namespace: demo-apps
  labels:
    app.kubernetes.io/name: demo-apps
    app.kubernetes.io/component: secret
type: Opaque
data:
  # API Processing Secrets (base64 encoded - replace with actual values)
  api-processing-storage-account-url: ""
  api-processing-storage-container: ""
  api-processing-processed-base-url: ""
  api-processing-servicebus-fqdn: ""
  api-processing-servicebus-queue: ""
  api-processing-appinsights-connection-string: ""
  
  # API Status Secrets (base64 encoded - replace with actual values)
  api-status-cosmos-account-url: ""
  api-status-cosmos-db-name: ""
  api-status-cosmos-container-name: ""
  api-status-appinsights-connection-string: ""
