apiVersion: v1
kind: Secret
metadata:
  name: demo-apps-secret
  namespace: demo-apps
data:
  # West US specific endpoints (base64 encoded)
  api-processing-storage-account-url: "aHR0cHM6Ly93ZXN0dXMtc3RvcmFnZS5ibG9iLmNvcmUud2luZG93cy5uZXQ="
  api-processing-servicebus-fqdn: "d2VzdHVzLXNlcnZpY2VidXMuc2VydmljZWJ1cy53aW5kb3dzLm5ldA=="
  api-status-cosmos-account-url: "aHR0cHM6Ly93ZXN0dXMtY29zbW9zLmRvY3VtZW50cy5henVyZS5jb206NDQzLw=="
