apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-apps-config
  namespace: demo-apps
data:
  environment: "prod"
  # Production West US URLs
  react-app-api-processing-url: "https://westus-api.example.com/api/processing"
  react-app-api-status-url: "https://westus-api.example.com/api/status"
